run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - revive
    - gofmt
    - misspell
    - unconvert
    - bodyclose

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
